# ===============================================
# MCP Agent Configuration
# ===============================================

agents:
  technical:
    class_name: "TechnicalAgent"
    description: "기술적 분석 기반 단기 추세 예측 모델 (TCN)"
    input_dim: 10
    hidden_dim: 64
    dropout: 0.1

  fundamental:
    class_name: "FundamentalAgent"
    description: "재무 데이터 기반 기업가치 예측 모델 (LSTM)"
    input_dim: 16
    hidden_dim: 64
    num_layers: 2
    dropout: 0.1

  sentimental:
    class_name: "SentimentalAgent"
    description: "투자자 심리 및 뉴스 감성 기반 시장 예측 모델 (Transformer)"
    input_dim: 8
    d_model: 64
    nhead: 4
    num_layers: 2
    dropout: 0.1
