# ===============================================
# MCP Agent Configuration
# ===============================================

agents:
  TechnicalAgent:
    col : ["Open", "High", "Low", "Close", "Volume", "returns", "sma_5", "sma_20", "rsi", "volume_z"]

  FundamentalAgent:
    col : ["Close", "USD_KRW", "NASDAQ", "VIX", "priceEarningsRatio", "forwardPE", "priceToBook", "debtEquityRatio", "returnOnAssets", "returnOnEquity", "profitMargins", "grossMargins"]

  SentimentalAgent:
    col : ["returns", "sentiment_mean", "sentiment_vol", "Close", "Volume", "Open", "High", "Low"]