# ===============================================
# MCP Training & Debate Hyperparameters
# ===============================================

pretraining:
  epochs: 20
  learning_rate: 0.001
  batch_size: 32

debate:
  rounds: 3
  temperature: 0.8
  reasoning_model: "gpt-5"      # LLM 모델명 (실제 API 호출 시 사용)
  max_tokens: 1024
  consensus_strategy: "mean"    # [mean, weighted, majority]
