nasdaq100_eng = {
    "NVIDIA": "NVDA",
    "Microsoft": "MSFT",
    "Apple": "AAPL",
    "Alphabet Class C": "GOOG",
    "Alphabet Class A": "GOOGL",
    "Amazon.com": "AMZN",
    "Meta Platforms": "META",
    "Broadcom": "AVGO",
    "Tesla": "TSLA",
    "Netflix": "NFLX",
    "Costco Wholesale": "COST",
    "Palantir Technologies Class A": "PLTR",
    "ASML Holding ADR": "ASML",
    "T-Mobile US": "TMUS",
    "Cisco Systems": "CSCO",
    "Advanced Micro Devices": "AMD",
    "AstraZeneca ADR": "AZN",
    "Linde": "LIN",
    "PepsiCo": "PEP",
    "AppLovin Class A": "APP",
    "Intuit": "INTU",
    "Shopify": "SHOP",
    "Booking Holdings": "BKNG",
    "Pinduoduo ADR": "PDD",
    "Qualcomm": "QCOM",
    "Texas Instruments": "TXN",
    "Intuitive Surgical": "ISRG",
    "Micron Technology": "MU",
    "Amgen": "AMGN",
    "Adobe": "ADBE",
    "Arm Holdings ADR": "ARM",
    "Gilead Sciences": "GILD",
    "Honeywell International": "HON",
    "Lam Research": "LRCX",
    "Palo Alto Networks": "PANW",
    "Applied Materials": "AMAT",
    "Comcast": "CMCSA",
    "Analog Devices": "ADI",
    "KLA": "KLAC",
    "Automatic Data Processing": "ADP",
    "MercadoLibre": "MELI",
    "Intel": "INTC",
    "Synopsys": "SNPS",
    "DoorDash": "DASH",
    "CrowdStrike Holdings": "CRWD",
    "Vertex Pharmaceuticals": "VRTX",
    "Cadence Design Systems": "CDNS",
    "Starbucks": "SBUX",
    "Constellation Energy": "CEG",
    "MicroStrategy": "MSTR",
    "O'Reilly Automotive": "ORLY",
    "Cintas": "CTAS",
    "Mondelez International": "MDLZ",
    "Thomson Reuters": "TRI",
    "Airbnb": "ABNB",
    "Marriott International": "MAR",
    "Autodesk": "ADSK",
    "PayPal Holdings": "PYPL",
    "Monster Beverage": "MNST",
    "Workday": "WDAY",
    "Fortinet": "FTNT",
    "CSX": "CSX",
    "Regeneron Pharmaceuticals": "REGN",
    "American Electric Power": "AEP",
    "Marvell Technology": "MRVL",
    "Axon Enterprise": "AXON",
    "NXP Semiconductors": "NXPI",
    "Roper Technologies": "ROP",
    "Fastenal": "FAST",
    "IDEXX Laboratories": "IDXX",
    "PACCAR": "PCAR",
    "Datadog": "DDOG",
    "Ross Stores": "ROST",
    "Paychex": "PAYX",
    "Atlassian": "TEAM",
    "Copart": "CPRT",
    "Take-Two Interactive": "TTWO",
    "Baker Hughes": "BKR",
    "Zscaler": "ZS",
    "Exelon": "EXC",
    "Xcel Energy": "XEL",
    "Coca-Cola Europacific Partners": "CCEP",
    "Electronic Arts": "EA",
    "Diamondback Energy": "FANG",
    "Verisk Analytics": "VRSK",
    "Keurig Dr Pepper": "KDP",
    "CoStar Group": "CSGP",
    "Charter Communications": "CHTR",
    "GE HealthCare Technologies": "GEHC",
    "Microchip Technology": "MCHP",
    "Cognizant Technology Solutions": "CTSH",
    "Kraft Heinz": "KHC",
    "Old Dominion Freight Line": "ODFL",
    "Dexcom": "DXCM",
    "Warner Bros. Discovery": "WBD",
    "Trade Desk": "TTD",
    "CDW": "CDW",
    "Biogen": "BIIB",
    "ON Semiconductor": "ON",
    "Lululemon Athletica": "LULU",
    "GlobalFoundries": "GFS"
}
